language: node_js
node_js:
- '0.10'
- '0.11'
before_script:
- psql -c 'create database "azul_test";' -U postgres
- mysql -e 'create database `azul_test`;'
env: PG_USER=postgres MYSQL_USER=travis
matrix:
  allow_failures:
  - node_js: '0.11'
